/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const LightscribeExportRecord = IDL.Record({
  'id' : IDL.Text,
  'exportType' : IDL.Text,
  'timestamp' : IDL.Nat,
  'labelProjectId' : IDL.Text,
  'fileReference' : ExternalBlob,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ArtistProfile = IDL.Record({
  'id' : IDL.Text,
  'bio' : IDL.Text,
  'portfolio' : IDL.Vec(IDL.Text),
  'contactInfo' : IDL.Text,
  'name' : IDL.Text,
  'elasticStageArtistUrl' : IDL.Opt(IDL.Text),
  'licensingInfo' : IDL.Text,
  'elasticStageArtistId' : IDL.Opt(IDL.Text),
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const LightscribeLabelProject = IDL.Record({
  'id' : IDL.Text,
  'previewImage' : ExternalBlob,
  'projectName' : IDL.Text,
  'exportHistory' : IDL.Vec(LightscribeExportRecord),
  'modifiedTimestamp' : IDL.Nat,
  'canvasData' : IDL.Text,
  'metadata' : IDL.Text,
  'artistId' : IDL.Text,
  'description' : IDL.Text,
  'layerData' : IDL.Text,
  'lsaFile' : ExternalBlob,
  'createdTimestamp' : IDL.Nat,
  'printableImage' : ExternalBlob,
  'labelScriptFile' : ExternalBlob,
  'lssFile' : ExternalBlob,
});
export const TrademarkRecord = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'documentReference' : IDL.Opt(ExternalBlob),
  'artistId' : IDL.Text,
  'description' : IDL.Text,
  'registrationNumber' : IDL.Text,
  'markName' : IDL.Text,
  'filingDate' : IDL.Nat,
});
export const PaymentMethod = IDL.Variant({
  'stripe' : IDL.Null,
  'merchantServices' : IDL.Null,
  'nationalBankcard' : IDL.Null,
});
export const CheckoutRequest = IDL.Record({
  'paymentMethod' : PaymentMethod,
  'cancelUrl' : IDL.Text,
  'buyerId' : IDL.Text,
  'items' : IDL.Vec(ShoppingItem),
  'successUrl' : IDL.Text,
});
export const CheckoutSessionResponse = IDL.Record({
  'paymentMethod' : PaymentMethod,
  'redirectUrl' : IDL.Opt(IDL.Text),
  'message' : IDL.Text,
  'sessionId' : IDL.Opt(IDL.Text),
});
export const EventCount = IDL.Record({
  'count' : IDL.Nat,
  'eventType' : IDL.Text,
});
export const RefAggregatedCounts = IDL.Record({
  'ref' : IDL.Opt(IDL.Text),
  'total' : IDL.Nat,
  'events' : IDL.Vec(EventCount),
});
export const RefAnalyticsSummary = IDL.Record({
  'refCounts' : IDL.Vec(RefAggregatedCounts),
  'lastUpdated' : IDL.Nat,
  'totalEvents' : IDL.Nat,
});
export const LicensingOption = IDL.Record({
  'id' : IDL.Text,
  'terms' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'price' : IDL.Nat,
});
export const ArtworkCategory = IDL.Variant({
  'musicalWorks' : IDL.Null,
  'narrativeArts' : IDL.Null,
  'artsAndCrafts' : IDL.Null,
  'artDesigns' : IDL.Null,
  'cinemaCreation' : IDL.Null,
  'scoreSheets' : IDL.Null,
  'poetry' : IDL.Null,
  'photography' : IDL.Null,
});
export const MediaType = IDL.Variant({
  'music' : IDL.Null,
  'video' : IDL.Null,
  'text' : IDL.Null,
  'image' : IDL.Null,
});
export const SaleFormat = IDL.Record({
  'formatType' : IDL.Text,
  'description' : IDL.Text,
  'price' : IDL.Nat,
});
export const MediaMetadata = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'licensingOptions' : IDL.Vec(LicensingOption),
  'artistId' : IDL.Text,
  'description' : IDL.Text,
  'copyrightInfo' : IDL.Text,
  'artworkCategory' : IDL.Opt(ArtworkCategory),
  'mediaType' : MediaType,
  'fileReference' : ExternalBlob,
  'saleFormats' : IDL.Vec(SaleFormat),
});
export const InvoiceRecord = IDL.Record({
  'id' : IDL.Text,
  'artistId' : IDL.Text,
  'description' : IDL.Text,
  'currency' : IDL.Text,
  'notes' : IDL.Opt(IDL.Text),
  'timestamp' : IDL.Nat,
  'amount' : IDL.Nat,
  'mediaId' : IDL.Opt(IDL.Text),
});
export const LightscribeTemplate = IDL.Record({
  'name' : IDL.Text,
  'createdBy' : IDL.Text,
  'description' : IDL.Text,
  'templateType' : IDL.Text,
  'createdTimestamp' : IDL.Nat,
  'fileReference' : ExternalBlob,
});
export const MembershipFeeRecord = IDL.Record({
  'id' : IDL.Text,
  'artistId' : IDL.Text,
  'currency' : IDL.Text,
  'notes' : IDL.Opt(IDL.Text),
  'timestamp' : IDL.Nat,
  'amount' : IDL.Nat,
});
export const PayoutRecord = IDL.Record({
  'id' : IDL.Text,
  'payoutMethod' : IDL.Text,
  'destinationAccount' : IDL.Text,
  'artistId' : IDL.Text,
  'currency' : IDL.Text,
  'notes' : IDL.Opt(IDL.Text),
  'associatedMediaId' : IDL.Opt(IDL.Text),
  'timestamp' : IDL.Nat,
  'amount' : IDL.Nat,
});
export const PurchaseRecord = IDL.Record({
  'id' : IDL.Text,
  'licensingOptionId' : IDL.Text,
  'buyerId' : IDL.Text,
  'timestamp' : IDL.Nat,
  'mediaId' : IDL.Text,
});
export const UserWithRole = IDL.Record({
  'userId' : IDL.Principal,
  'name' : IDL.Text,
  'role' : IDL.Text,
  'email' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const MerchantServicesConfig = IDL.Record({
  'transactionKey' : IDL.Text,
  'endpoint' : IDL.Text,
  'allowedCountries' : IDL.Vec(IDL.Text),
  'apiLoginId' : IDL.Text,
});
export const NationalBankcardConfig = IDL.Record({
  'endpoint' : IDL.Text,
  'allowedCountries' : IDL.Vec(IDL.Text),
  'merchantId' : IDL.Text,
  'apiKey' : IDL.Text,
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addExportRecord' : IDL.Func([LightscribeExportRecord], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignUserRole' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'createArtistProfile' : IDL.Func([ArtistProfile], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createInvoiceRecord' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [IDL.Text],
      [],
    ),
  'createLightscribeProject' : IDL.Func([LightscribeLabelProject], [], []),
  'createMembershipFeeRecord' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Opt(IDL.Text)],
      [IDL.Text],
      [],
    ),
  'createPayoutRecord' : IDL.Func(
      [
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [IDL.Text],
      [],
    ),
  'createTrademarkRecord' : IDL.Func([TrademarkRecord], [], []),
  'createUnifiedCheckoutSession' : IDL.Func(
      [CheckoutRequest],
      [CheckoutSessionResponse],
      [],
    ),
  'deleteArtistProfile' : IDL.Func([IDL.Text], [], []),
  'deleteInvoiceRecord' : IDL.Func([IDL.Text], [], []),
  'deleteLightscribeProject' : IDL.Func([IDL.Text], [], []),
  'deleteMedia' : IDL.Func([IDL.Text], [], []),
  'deleteMembershipFeeRecord' : IDL.Func([IDL.Text], [], []),
  'deletePayoutRecord' : IDL.Func([IDL.Text], [], []),
  'deleteTrademarkRecord' : IDL.Func([IDL.Text], [], []),
  'deleteUser' : IDL.Func([IDL.Principal], [], []),
  'getAllAnalyticsData' : IDL.Func([], [RefAnalyticsSummary], []),
  'getAllArtistProfiles' : IDL.Func([], [IDL.Vec(ArtistProfile)], ['query']),
  'getAllGalleryMedia' : IDL.Func([], [IDL.Vec(MediaMetadata)], ['query']),
  'getAllInvoiceRecords' : IDL.Func([], [IDL.Vec(InvoiceRecord)], ['query']),
  'getAllLightscribeTemplates' : IDL.Func(
      [],
      [IDL.Vec(LightscribeTemplate)],
      ['query'],
    ),
  'getAllMedia' : IDL.Func([], [IDL.Vec(MediaMetadata)], ['query']),
  'getAllMembershipFeeRecords' : IDL.Func(
      [],
      [IDL.Vec(MembershipFeeRecord)],
      ['query'],
    ),
  'getAllPayoutRecords' : IDL.Func([], [IDL.Vec(PayoutRecord)], ['query']),
  'getAllPurchaseRecords' : IDL.Func([], [IDL.Vec(PurchaseRecord)], ['query']),
  'getAllUsersWithRoles' : IDL.Func([], [IDL.Vec(UserWithRole)], ['query']),
  'getArtistProfile' : IDL.Func([IDL.Text], [ArtistProfile], ['query']),
  'getArtistSales' : IDL.Func([IDL.Text], [IDL.Vec(PurchaseRecord)], ['query']),
  'getArtistTrademarks' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(TrademarkRecord)],
      ['query'],
    ),
  'getArtistWorks' : IDL.Func([IDL.Text], [IDL.Vec(MediaMetadata)], ['query']),
  'getArtistWorksByCategory' : IDL.Func(
      [IDL.Text, ArtworkCategory],
      [IDL.Vec(MediaMetadata)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getInvoiceRecord' : IDL.Func([IDL.Text], [InvoiceRecord], ['query']),
  'getLicensingOptions' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(LicensingOption)],
      ['query'],
    ),
  'getLightscribeProject' : IDL.Func(
      [IDL.Text],
      [LightscribeLabelProject],
      ['query'],
    ),
  'getLightscribeTemplateByName' : IDL.Func(
      [IDL.Text],
      [LightscribeTemplate],
      ['query'],
    ),
  'getMedia' : IDL.Func([IDL.Text], [MediaMetadata], ['query']),
  'getMediaByCategory' : IDL.Func(
      [ArtworkCategory],
      [IDL.Vec(MediaMetadata)],
      ['query'],
    ),
  'getMediaByType' : IDL.Func([MediaType], [IDL.Vec(MediaMetadata)], ['query']),
  'getMembershipFeeRecord' : IDL.Func(
      [IDL.Text],
      [MembershipFeeRecord],
      ['query'],
    ),
  'getMyLightscribeProjects' : IDL.Func(
      [],
      [IDL.Vec(LightscribeLabelProject)],
      ['query'],
    ),
  'getMyPurchases' : IDL.Func([], [IDL.Vec(PurchaseRecord)], ['query']),
  'getMyTrademarks' : IDL.Func([], [IDL.Vec(TrademarkRecord)], ['query']),
  'getPayoutRecord' : IDL.Func([IDL.Text], [PayoutRecord], ['query']),
  'getProjectExportHistory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(LightscribeExportRecord)],
      ['query'],
    ),
  'getPurchaseRecord' : IDL.Func([IDL.Text], [PurchaseRecord], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getTrademarkRecord' : IDL.Func([IDL.Text], [TrademarkRecord], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isMerchantServicesConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'isNationalBankcardConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'purchaseLicense' : IDL.Func([PurchaseRecord], [], []),
  'recordEvent' : IDL.Func(
      [
        IDL.Record({ 'caller' : IDL.Principal }),
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveLightscribeTemplate' : IDL.Func([LightscribeTemplate], [], []),
  'searchMediaByKeyword' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(MediaMetadata)],
      ['query'],
    ),
  'setMerchantServicesConfiguration' : IDL.Func(
      [MerchantServicesConfig],
      [],
      [],
    ),
  'setNationalBankcardConfiguration' : IDL.Func(
      [NationalBankcardConfig],
      [],
      [],
    ),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateArtistProfile' : IDL.Func([ArtistProfile], [], []),
  'updateInvoiceRecord' : IDL.Func([InvoiceRecord], [], []),
  'updateLightscribeProject' : IDL.Func([LightscribeLabelProject], [], []),
  'updateMedia' : IDL.Func([MediaMetadata], [], []),
  'updateMembershipFeeRecord' : IDL.Func([MembershipFeeRecord], [], []),
  'updatePayoutRecord' : IDL.Func([PayoutRecord], [], []),
  'updateTrademarkRecord' : IDL.Func([TrademarkRecord], [], []),
  'uploadMedia' : IDL.Func([MediaMetadata], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const LightscribeExportRecord = IDL.Record({
    'id' : IDL.Text,
    'exportType' : IDL.Text,
    'timestamp' : IDL.Nat,
    'labelProjectId' : IDL.Text,
    'fileReference' : ExternalBlob,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ArtistProfile = IDL.Record({
    'id' : IDL.Text,
    'bio' : IDL.Text,
    'portfolio' : IDL.Vec(IDL.Text),
    'contactInfo' : IDL.Text,
    'name' : IDL.Text,
    'elasticStageArtistUrl' : IDL.Opt(IDL.Text),
    'licensingInfo' : IDL.Text,
    'elasticStageArtistId' : IDL.Opt(IDL.Text),
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const LightscribeLabelProject = IDL.Record({
    'id' : IDL.Text,
    'previewImage' : ExternalBlob,
    'projectName' : IDL.Text,
    'exportHistory' : IDL.Vec(LightscribeExportRecord),
    'modifiedTimestamp' : IDL.Nat,
    'canvasData' : IDL.Text,
    'metadata' : IDL.Text,
    'artistId' : IDL.Text,
    'description' : IDL.Text,
    'layerData' : IDL.Text,
    'lsaFile' : ExternalBlob,
    'createdTimestamp' : IDL.Nat,
    'printableImage' : ExternalBlob,
    'labelScriptFile' : ExternalBlob,
    'lssFile' : ExternalBlob,
  });
  const TrademarkRecord = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'documentReference' : IDL.Opt(ExternalBlob),
    'artistId' : IDL.Text,
    'description' : IDL.Text,
    'registrationNumber' : IDL.Text,
    'markName' : IDL.Text,
    'filingDate' : IDL.Nat,
  });
  const PaymentMethod = IDL.Variant({
    'stripe' : IDL.Null,
    'merchantServices' : IDL.Null,
    'nationalBankcard' : IDL.Null,
  });
  const CheckoutRequest = IDL.Record({
    'paymentMethod' : PaymentMethod,
    'cancelUrl' : IDL.Text,
    'buyerId' : IDL.Text,
    'items' : IDL.Vec(ShoppingItem),
    'successUrl' : IDL.Text,
  });
  const CheckoutSessionResponse = IDL.Record({
    'paymentMethod' : PaymentMethod,
    'redirectUrl' : IDL.Opt(IDL.Text),
    'message' : IDL.Text,
    'sessionId' : IDL.Opt(IDL.Text),
  });
  const EventCount = IDL.Record({ 'count' : IDL.Nat, 'eventType' : IDL.Text });
  const RefAggregatedCounts = IDL.Record({
    'ref' : IDL.Opt(IDL.Text),
    'total' : IDL.Nat,
    'events' : IDL.Vec(EventCount),
  });
  const RefAnalyticsSummary = IDL.Record({
    'refCounts' : IDL.Vec(RefAggregatedCounts),
    'lastUpdated' : IDL.Nat,
    'totalEvents' : IDL.Nat,
  });
  const LicensingOption = IDL.Record({
    'id' : IDL.Text,
    'terms' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'price' : IDL.Nat,
  });
  const ArtworkCategory = IDL.Variant({
    'musicalWorks' : IDL.Null,
    'narrativeArts' : IDL.Null,
    'artsAndCrafts' : IDL.Null,
    'artDesigns' : IDL.Null,
    'cinemaCreation' : IDL.Null,
    'scoreSheets' : IDL.Null,
    'poetry' : IDL.Null,
    'photography' : IDL.Null,
  });
  const MediaType = IDL.Variant({
    'music' : IDL.Null,
    'video' : IDL.Null,
    'text' : IDL.Null,
    'image' : IDL.Null,
  });
  const SaleFormat = IDL.Record({
    'formatType' : IDL.Text,
    'description' : IDL.Text,
    'price' : IDL.Nat,
  });
  const MediaMetadata = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'licensingOptions' : IDL.Vec(LicensingOption),
    'artistId' : IDL.Text,
    'description' : IDL.Text,
    'copyrightInfo' : IDL.Text,
    'artworkCategory' : IDL.Opt(ArtworkCategory),
    'mediaType' : MediaType,
    'fileReference' : ExternalBlob,
    'saleFormats' : IDL.Vec(SaleFormat),
  });
  const InvoiceRecord = IDL.Record({
    'id' : IDL.Text,
    'artistId' : IDL.Text,
    'description' : IDL.Text,
    'currency' : IDL.Text,
    'notes' : IDL.Opt(IDL.Text),
    'timestamp' : IDL.Nat,
    'amount' : IDL.Nat,
    'mediaId' : IDL.Opt(IDL.Text),
  });
  const LightscribeTemplate = IDL.Record({
    'name' : IDL.Text,
    'createdBy' : IDL.Text,
    'description' : IDL.Text,
    'templateType' : IDL.Text,
    'createdTimestamp' : IDL.Nat,
    'fileReference' : ExternalBlob,
  });
  const MembershipFeeRecord = IDL.Record({
    'id' : IDL.Text,
    'artistId' : IDL.Text,
    'currency' : IDL.Text,
    'notes' : IDL.Opt(IDL.Text),
    'timestamp' : IDL.Nat,
    'amount' : IDL.Nat,
  });
  const PayoutRecord = IDL.Record({
    'id' : IDL.Text,
    'payoutMethod' : IDL.Text,
    'destinationAccount' : IDL.Text,
    'artistId' : IDL.Text,
    'currency' : IDL.Text,
    'notes' : IDL.Opt(IDL.Text),
    'associatedMediaId' : IDL.Opt(IDL.Text),
    'timestamp' : IDL.Nat,
    'amount' : IDL.Nat,
  });
  const PurchaseRecord = IDL.Record({
    'id' : IDL.Text,
    'licensingOptionId' : IDL.Text,
    'buyerId' : IDL.Text,
    'timestamp' : IDL.Nat,
    'mediaId' : IDL.Text,
  });
  const UserWithRole = IDL.Record({
    'userId' : IDL.Principal,
    'name' : IDL.Text,
    'role' : IDL.Text,
    'email' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const MerchantServicesConfig = IDL.Record({
    'transactionKey' : IDL.Text,
    'endpoint' : IDL.Text,
    'allowedCountries' : IDL.Vec(IDL.Text),
    'apiLoginId' : IDL.Text,
  });
  const NationalBankcardConfig = IDL.Record({
    'endpoint' : IDL.Text,
    'allowedCountries' : IDL.Vec(IDL.Text),
    'merchantId' : IDL.Text,
    'apiKey' : IDL.Text,
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addExportRecord' : IDL.Func([LightscribeExportRecord], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignUserRole' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'createArtistProfile' : IDL.Func([ArtistProfile], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createInvoiceRecord' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [IDL.Text],
        [],
      ),
    'createLightscribeProject' : IDL.Func([LightscribeLabelProject], [], []),
    'createMembershipFeeRecord' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Opt(IDL.Text)],
        [IDL.Text],
        [],
      ),
    'createPayoutRecord' : IDL.Func(
        [
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [IDL.Text],
        [],
      ),
    'createTrademarkRecord' : IDL.Func([TrademarkRecord], [], []),
    'createUnifiedCheckoutSession' : IDL.Func(
        [CheckoutRequest],
        [CheckoutSessionResponse],
        [],
      ),
    'deleteArtistProfile' : IDL.Func([IDL.Text], [], []),
    'deleteInvoiceRecord' : IDL.Func([IDL.Text], [], []),
    'deleteLightscribeProject' : IDL.Func([IDL.Text], [], []),
    'deleteMedia' : IDL.Func([IDL.Text], [], []),
    'deleteMembershipFeeRecord' : IDL.Func([IDL.Text], [], []),
    'deletePayoutRecord' : IDL.Func([IDL.Text], [], []),
    'deleteTrademarkRecord' : IDL.Func([IDL.Text], [], []),
    'deleteUser' : IDL.Func([IDL.Principal], [], []),
    'getAllAnalyticsData' : IDL.Func([], [RefAnalyticsSummary], []),
    'getAllArtistProfiles' : IDL.Func([], [IDL.Vec(ArtistProfile)], ['query']),
    'getAllGalleryMedia' : IDL.Func([], [IDL.Vec(MediaMetadata)], ['query']),
    'getAllInvoiceRecords' : IDL.Func([], [IDL.Vec(InvoiceRecord)], ['query']),
    'getAllLightscribeTemplates' : IDL.Func(
        [],
        [IDL.Vec(LightscribeTemplate)],
        ['query'],
      ),
    'getAllMedia' : IDL.Func([], [IDL.Vec(MediaMetadata)], ['query']),
    'getAllMembershipFeeRecords' : IDL.Func(
        [],
        [IDL.Vec(MembershipFeeRecord)],
        ['query'],
      ),
    'getAllPayoutRecords' : IDL.Func([], [IDL.Vec(PayoutRecord)], ['query']),
    'getAllPurchaseRecords' : IDL.Func(
        [],
        [IDL.Vec(PurchaseRecord)],
        ['query'],
      ),
    'getAllUsersWithRoles' : IDL.Func([], [IDL.Vec(UserWithRole)], ['query']),
    'getArtistProfile' : IDL.Func([IDL.Text], [ArtistProfile], ['query']),
    'getArtistSales' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(PurchaseRecord)],
        ['query'],
      ),
    'getArtistTrademarks' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(TrademarkRecord)],
        ['query'],
      ),
    'getArtistWorks' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(MediaMetadata)],
        ['query'],
      ),
    'getArtistWorksByCategory' : IDL.Func(
        [IDL.Text, ArtworkCategory],
        [IDL.Vec(MediaMetadata)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getInvoiceRecord' : IDL.Func([IDL.Text], [InvoiceRecord], ['query']),
    'getLicensingOptions' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(LicensingOption)],
        ['query'],
      ),
    'getLightscribeProject' : IDL.Func(
        [IDL.Text],
        [LightscribeLabelProject],
        ['query'],
      ),
    'getLightscribeTemplateByName' : IDL.Func(
        [IDL.Text],
        [LightscribeTemplate],
        ['query'],
      ),
    'getMedia' : IDL.Func([IDL.Text], [MediaMetadata], ['query']),
    'getMediaByCategory' : IDL.Func(
        [ArtworkCategory],
        [IDL.Vec(MediaMetadata)],
        ['query'],
      ),
    'getMediaByType' : IDL.Func(
        [MediaType],
        [IDL.Vec(MediaMetadata)],
        ['query'],
      ),
    'getMembershipFeeRecord' : IDL.Func(
        [IDL.Text],
        [MembershipFeeRecord],
        ['query'],
      ),
    'getMyLightscribeProjects' : IDL.Func(
        [],
        [IDL.Vec(LightscribeLabelProject)],
        ['query'],
      ),
    'getMyPurchases' : IDL.Func([], [IDL.Vec(PurchaseRecord)], ['query']),
    'getMyTrademarks' : IDL.Func([], [IDL.Vec(TrademarkRecord)], ['query']),
    'getPayoutRecord' : IDL.Func([IDL.Text], [PayoutRecord], ['query']),
    'getProjectExportHistory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(LightscribeExportRecord)],
        ['query'],
      ),
    'getPurchaseRecord' : IDL.Func([IDL.Text], [PurchaseRecord], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getTrademarkRecord' : IDL.Func([IDL.Text], [TrademarkRecord], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isMerchantServicesConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'isNationalBankcardConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'purchaseLicense' : IDL.Func([PurchaseRecord], [], []),
    'recordEvent' : IDL.Func(
        [
          IDL.Record({ 'caller' : IDL.Principal }),
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveLightscribeTemplate' : IDL.Func([LightscribeTemplate], [], []),
    'searchMediaByKeyword' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(MediaMetadata)],
        ['query'],
      ),
    'setMerchantServicesConfiguration' : IDL.Func(
        [MerchantServicesConfig],
        [],
        [],
      ),
    'setNationalBankcardConfiguration' : IDL.Func(
        [NationalBankcardConfig],
        [],
        [],
      ),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateArtistProfile' : IDL.Func([ArtistProfile], [], []),
    'updateInvoiceRecord' : IDL.Func([InvoiceRecord], [], []),
    'updateLightscribeProject' : IDL.Func([LightscribeLabelProject], [], []),
    'updateMedia' : IDL.Func([MediaMetadata], [], []),
    'updateMembershipFeeRecord' : IDL.Func([MembershipFeeRecord], [], []),
    'updatePayoutRecord' : IDL.Func([PayoutRecord], [], []),
    'updateTrademarkRecord' : IDL.Func([TrademarkRecord], [], []),
    'uploadMedia' : IDL.Func([MediaMetadata], [], []),
  });
};

export const init = ({ IDL }) => { return []; };