/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ArtistProfile {
  'id' : string,
  'bio' : string,
  'portfolio' : Array<string>,
  'contactInfo' : string,
  'name' : string,
  'elasticStageArtistUrl' : [] | [string],
  'licensingInfo' : string,
  'elasticStageArtistId' : [] | [string],
}
export interface CheckoutRequest {
  'paymentMethod' : PaymentMethod,
  'cancelUrl' : string,
  'buyerId' : string,
  'items' : Array<ShoppingItem>,
  'successUrl' : string,
}
export interface CheckoutSessionResponse {
  'paymentMethod' : PaymentMethod,
  'redirectUrl' : [] | [string],
  'message' : string,
  'sessionId' : [] | [string],
}
export interface EventCount { 'count' : bigint, 'eventType' : string }
export type ExternalBlob = Uint8Array;
export interface InvoiceRecord {
  'id' : string,
  'artistId' : string,
  'description' : string,
  'currency' : string,
  'notes' : [] | [string],
  'timestamp' : bigint,
  'amount' : bigint,
  'mediaId' : [] | [string],
}
export interface LicensingOption {
  'id' : string,
  'terms' : string,
  'name' : string,
  'description' : string,
  'price' : bigint,
}
export interface LightscribeExportRecord {
  'id' : string,
  'exportType' : string,
  'timestamp' : bigint,
  'labelProjectId' : string,
  'fileReference' : ExternalBlob,
}
export interface LightscribeLabelProject {
  'id' : string,
  'previewImage' : ExternalBlob,
  'projectName' : string,
  'exportHistory' : Array<LightscribeExportRecord>,
  'modifiedTimestamp' : bigint,
  'canvasData' : string,
  'metadata' : string,
  'artistId' : string,
  'description' : string,
  'layerData' : string,
  'lsaFile' : ExternalBlob,
  'createdTimestamp' : bigint,
  'printableImage' : ExternalBlob,
  'labelScriptFile' : ExternalBlob,
  'lssFile' : ExternalBlob,
}
export interface LightscribeTemplate {
  'name' : string,
  'createdBy' : string,
  'description' : string,
  'templateType' : string,
  'createdTimestamp' : bigint,
  'fileReference' : ExternalBlob,
}
export interface MediaMetadata {
  'id' : string,
  'title' : string,
  'licensingOptions' : Array<LicensingOption>,
  'artistId' : string,
  'description' : string,
  'copyrightInfo' : string,
  'mediaType' : MediaType,
  'fileReference' : ExternalBlob,
}
export type MediaType = { 'music' : null } |
  { 'video' : null } |
  { 'text' : null } |
  { 'image' : null };
export interface MembershipFeeRecord {
  'id' : string,
  'artistId' : string,
  'currency' : string,
  'notes' : [] | [string],
  'timestamp' : bigint,
  'amount' : bigint,
}
export interface MerchantServicesConfig {
  'transactionKey' : string,
  'endpoint' : string,
  'allowedCountries' : Array<string>,
  'apiLoginId' : string,
}
export interface NationalBankcardConfig {
  'endpoint' : string,
  'allowedCountries' : Array<string>,
  'merchantId' : string,
  'apiKey' : string,
}
export type PaymentMethod = { 'stripe' : null } |
  { 'merchantServices' : null } |
  { 'nationalBankcard' : null };
export interface PayoutRecord {
  'id' : string,
  'payoutMethod' : string,
  'destinationAccount' : string,
  'artistId' : string,
  'currency' : string,
  'notes' : [] | [string],
  'associatedMediaId' : [] | [string],
  'timestamp' : bigint,
  'amount' : bigint,
}
export interface PurchaseRecord {
  'id' : string,
  'licensingOptionId' : string,
  'buyerId' : string,
  'timestamp' : bigint,
  'mediaId' : string,
}
export interface RefAggregatedCounts {
  'ref' : [] | [string],
  'total' : bigint,
  'events' : Array<EventCount>,
}
export interface RefAnalyticsSummary {
  'refCounts' : Array<RefAggregatedCounts>,
  'lastUpdated' : bigint,
  'totalEvents' : bigint,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface TrademarkRecord {
  'id' : string,
  'status' : string,
  'documentReference' : [] | [ExternalBlob],
  'artistId' : string,
  'description' : string,
  'registrationNumber' : string,
  'markName' : string,
  'filingDate' : bigint,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile { 'name' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserWithRole {
  'userId' : Principal,
  'name' : string,
  'role' : string,
  'email' : string,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addExportRecord' : ActorMethod<[LightscribeExportRecord], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignUserRole' : ActorMethod<[Principal, string], undefined>,
  'createArtistProfile' : ActorMethod<[ArtistProfile], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createInvoiceRecord' : ActorMethod<
    [string, bigint, string, [] | [string], [] | [string]],
    string
  >,
  'createLightscribeProject' : ActorMethod<
    [LightscribeLabelProject],
    undefined
  >,
  'createMembershipFeeRecord' : ActorMethod<
    [string, bigint, [] | [string]],
    string
  >,
  'createPayoutRecord' : ActorMethod<
    [string, bigint, string, string, [] | [string], [] | [string]],
    string
  >,
  'createTrademarkRecord' : ActorMethod<[TrademarkRecord], undefined>,
  'createUnifiedCheckoutSession' : ActorMethod<
    [CheckoutRequest],
    CheckoutSessionResponse
  >,
  'deleteArtistProfile' : ActorMethod<[string], undefined>,
  'deleteInvoiceRecord' : ActorMethod<[string], undefined>,
  'deleteLightscribeProject' : ActorMethod<[string], undefined>,
  'deleteMedia' : ActorMethod<[string], undefined>,
  'deleteMembershipFeeRecord' : ActorMethod<[string], undefined>,
  'deletePayoutRecord' : ActorMethod<[string], undefined>,
  'deleteTrademarkRecord' : ActorMethod<[string], undefined>,
  'deleteUser' : ActorMethod<[Principal], undefined>,
  'getAllAnalyticsData' : ActorMethod<[], RefAnalyticsSummary>,
  'getAllArtistProfiles' : ActorMethod<[], Array<ArtistProfile>>,
  'getAllInvoiceRecords' : ActorMethod<[], Array<InvoiceRecord>>,
  'getAllLightscribeTemplates' : ActorMethod<[], Array<LightscribeTemplate>>,
  'getAllMedia' : ActorMethod<[], Array<MediaMetadata>>,
  'getAllMembershipFeeRecords' : ActorMethod<[], Array<MembershipFeeRecord>>,
  'getAllPayoutRecords' : ActorMethod<[], Array<PayoutRecord>>,
  'getAllPurchaseRecords' : ActorMethod<[], Array<PurchaseRecord>>,
  'getAllUsersWithRoles' : ActorMethod<[], Array<UserWithRole>>,
  'getArtistProfile' : ActorMethod<[string], ArtistProfile>,
  'getArtistSales' : ActorMethod<[string], Array<PurchaseRecord>>,
  'getArtistTrademarks' : ActorMethod<[string], Array<TrademarkRecord>>,
  'getArtistWorks' : ActorMethod<[string], Array<MediaMetadata>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getInvoiceRecord' : ActorMethod<[string], InvoiceRecord>,
  'getLicensingOptions' : ActorMethod<[string], Array<LicensingOption>>,
  'getLightscribeProject' : ActorMethod<[string], LightscribeLabelProject>,
  'getLightscribeTemplateByName' : ActorMethod<[string], LightscribeTemplate>,
  'getMedia' : ActorMethod<[string], MediaMetadata>,
  'getMediaByType' : ActorMethod<[MediaType], Array<MediaMetadata>>,
  'getMembershipFeeRecord' : ActorMethod<[string], MembershipFeeRecord>,
  'getMyLightscribeProjects' : ActorMethod<[], Array<LightscribeLabelProject>>,
  'getMyPurchases' : ActorMethod<[], Array<PurchaseRecord>>,
  'getMyTrademarks' : ActorMethod<[], Array<TrademarkRecord>>,
  'getPayoutRecord' : ActorMethod<[string], PayoutRecord>,
  'getProjectExportHistory' : ActorMethod<
    [string],
    Array<LightscribeExportRecord>
  >,
  'getPurchaseRecord' : ActorMethod<[string], PurchaseRecord>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getTrademarkRecord' : ActorMethod<[string], TrademarkRecord>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isMerchantServicesConfigured' : ActorMethod<[], boolean>,
  'isNationalBankcardConfigured' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'purchaseLicense' : ActorMethod<[PurchaseRecord], undefined>,
  'recordEvent' : ActorMethod<
    [{ 'caller' : Principal }, string, [] | [string], [] | [string]],
    undefined
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveLightscribeTemplate' : ActorMethod<[LightscribeTemplate], undefined>,
  'searchMediaByKeyword' : ActorMethod<[string], Array<MediaMetadata>>,
  'setMerchantServicesConfiguration' : ActorMethod<
    [MerchantServicesConfig],
    undefined
  >,
  'setNationalBankcardConfiguration' : ActorMethod<
    [NationalBankcardConfig],
    undefined
  >,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateArtistProfile' : ActorMethod<[ArtistProfile], undefined>,
  'updateInvoiceRecord' : ActorMethod<[InvoiceRecord], undefined>,
  'updateLightscribeProject' : ActorMethod<
    [LightscribeLabelProject],
    undefined
  >,
  'updateMedia' : ActorMethod<[MediaMetadata], undefined>,
  'updateMembershipFeeRecord' : ActorMethod<[MembershipFeeRecord], undefined>,
  'updatePayoutRecord' : ActorMethod<[PayoutRecord], undefined>,
  'updateTrademarkRecord' : ActorMethod<[TrademarkRecord], undefined>,
  'uploadMedia' : ActorMethod<[MediaMetadata], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];